input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        run_id:
          display:
            description: A unique run identifier for tracking groups of workflows triggered by external automation/CI
            name: Run ID
          type:
            type_id: string
          default: "\"\""
          required: false
        user:
          display:
            description: A user name identifier for tracking groups of workflows triggered by external automation/CI
            name: User
          type:
            type_id: string
          default: "\"\""
          required: false
        cluster_name:
          display:
            description: A cluster name identifier for tracking groups of workflows triggered by external automation/CI
            name: Cluster Name
          type:
            type_id: string
          default: "\"\""
          required: false
        pmlogger_interval:
          display:
            description: The logger collection interval for PCP pmlogger
            name: PCP pmlogger collection interval
          type:
            type_id: integer
        sysbench_threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        sysbench_events:
          display:
            description: The number of events sysbench will run
            name: sysbench events
          type:
            type_id: integer
        sysbench_cpumaxprime:
          display:
            description: The upper limit of the number of prime numbers generated
            name: sysbench cpu max primes
          type:
            type_id: integer
        sysbench_runtime:
          display:
            description: The total runtime in seconds for the sysbench tests
            name: sysbench runtime seconds
          type:
            type_id: integer
        elastic_host:
          display:
            description: The host URL for the ElasticSearch service
            name: elasticsearch host url
          type:
            type_id: string
        elastic_username:
          display:
            description: The username for the ElasticSearch service
            name: elasticsearch username
          type:
            type_id: string
        elastic_password:
          display:
            description: The password for the ElasticSearch service
            name: elasticsearch password
          type:
            type_id: string
        elastic_index_sysbench:
          display:
            description: The index for the ElasticSearch service for sysbench
            name: elasticsearch index
          type:
            type_id: string
        elastic_index_pcp:
          display:
            description: The index for the ElasticSearch service for pcp
            name: elasticsearch index
          type:
            type_id: string
steps:
  uuidgen:
    plugin: quay.io/arcalot/arcaflow-plugin-utilities:latest
    step: uuid
    input: {}
  system_config:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
    input: {}
  pcp:
    plugin: quay.io/arcalot/arcaflow-plugin-pcp:0.2.0
    step: start-pcp
    input:
      pmlogger_interval: !expr $.input.pmlogger_interval
      run_duration: !expr $.input.sysbench_runtime
  sysbench:
    plugin: quay.io/arcalot/arcaflow-plugin-sysbench:0.1.0
    step: sysbenchcpu
    input:
      threads: !expr $.input.sysbench_threads
      events: !expr $.input.sysbench_events
      cpu-max-prime: !expr $.input.sysbench_cpumaxprime
      time: !expr $.input.sysbench_runtime
  elasticsearch_sysbench:
    plugin: quay.io/arcalot/arcaflow-plugin-opensearch:0.1.1
    input:
      url: !expr $.input.elastic_host
      username: !expr $.input.elastic_username
      password: !expr $.input.elastic_password
      index: !expr $.input.elastic_index_sysbench
      data:
        uuid: !expr $.steps.uuidgen.outputs.success.uuid
        run_id: !expr $.input.run_id
        user: !expr $.input.user
        cluster_name: !expr $.input.cluster_name
        system_config: !expr $.steps.system_config.outputs.success
        sysbench: !expr $.steps.sysbench.outputs.success
  elasticsearch_pcp:
    plugin: quay.io/arcalot/arcaflow-plugin-opensearch:0.1.1
    input:
      url: !expr $.input.elastic_host
      username: !expr $.input.elastic_username
      password: !expr $.input.elastic_password
      index: !expr $.input.elastic_index_pcp
      data:
        uuid: !expr $.steps.uuidgen.outputs.success.uuid
        run_id: !expr $.input.run_id
        user: !expr $.input.user
        cluster_name: !expr $.input.cluster_name
        system_config: !expr $.steps.system_config.outputs.success
        pcp: !expr $.steps.pcp.outputs.success
output:
  uuid: !expr $.steps.uuidgen.outputs.success.uuid
  run_id: !expr $.input.run_id
  user: !expr $.input.user
  cluster_name: !expr $.input.cluster_name
  system_config: !expr $.steps.system_config.outputs.success
  pcp: !expr $.steps.pcp.outputs.success
  sysbench: !expr $.steps.sysbench.outputs.success
  elasticsearch_sysbench: !expr $.steps.elasticsearch_sysbench.outputs.success
  elasticsearch_pcp: !expr $.steps.elasticsearch_pcp.outputs.success
