version: v0.2.0
input:
  root: SysbenchLoopWorkflowInput
  objects:
    SysbenchCpuInputParams:
      id: SysbenchCpuInputParams
      properties:
        threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        time:
          display:
            description: The maximum runtime in seconds for the sysbench tests
            name: sysbench max runtime seconds
          type:
            type_id: integer
        percentile:
          display:
            description: The percentile to report latency metrics
            name: sysbench latency percentile
          type:
            type_id: integer
        cpu-max-prime:
          display:
            description: The upper limit of the number of prime numbers generated
            name: sysbench cpu max primes
          type:
            type_id: integer
    SysbenchMemoryInputParams:
      id: SysbenchMemoryInputParams
      properties:
        threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        time:
          display:
            description: The maximum runtime in seconds for the sysbench tests
            name: sysbench max runtime seconds
          type:
            type_id: integer
        percentile:
          display:
            description: The percentile to report latency metrics
            name: sysbench latency percentile
          type:
            type_id: integer
        memory-total-size:
          display:
            name: Total size of data to transfer in GiB
          required: false
          type:
            type_id: string
    PcpInputParams:
      id: PcpInputParams
      properties:
        pmlogger_interval:
          display:
            description: The logger collection interval for PCP pmlogger
            name: PCP pmlogger collection interval
          type:
            type_id: float
          required: false
          default: 1.0
    SysbenchLoopWorkflowInput:
      id: SysbenchLoopWorkflowInput
      properties:
        run_id:
          display:
            description: A unique run identifier for tracking groups of workflows triggered by external automation/CI
            name: Run ID
          type:
            type_id: string
          default: "\"\""
          required: false
        user:
          display:
            description: A user name identifier for tracking groups of workflows triggered by external automation/CI
            name: User
          type:
            type_id: string
          default: "\"\""
          required: false
        sysbench_cpu_tests:
          type:
            type_id: list
            items:
              type_id: object
              id: SysbenchCpuWorkflowInput
              properties:
                sysbench_params:
                  type:
                    type_id: ref
                    id: SysbenchCpuInputParams
                pcp_params:
                  type:
                    type_id: ref
                    id: PcpInputParams
        sysbench_memory_tests:
          type:
            type_id: list
            items:
              type_id: object
              id: SysbenchMemoryWorkflowInput
              properties:
                sysbench_params:
                  type:
                    type_id: ref
                    id: SysbenchMemoryInputParams
                pcp_params:
                  type:
                    type_id: ref
                    id: PcpInputParams

steps:
  uuidgen:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-utilities:0.4.0
    step: uuid
    input: {}
  system_config:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-metadata:0.4.0
    input: {}
  sysbench_cpu_loop:
    kind: foreach
    items: !expr $.input.sysbench_cpu_tests
    workflow: sysbench-cpu.yaml
    parallelism: 1

outputs:
  success:
    uuid: !expr $.steps.uuidgen.outputs.success.uuid
    run_id: !expr $.input.run_id
    user: !expr $.input.user
    system_config: !expr $.steps.system_config.outputs.success
    sysbench_cpu: !expr $.steps.sysbench_cpu_loop.outputs.success
