version: v0.2.0
input:
  root: SysbenchLoopWorkflowInput
  objects:
    SysbenchCpuInputParams:
      id: SysbenchCpuInputParams
      properties:
        threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        time:
          display:
            description: The maximum runtime in seconds for the sysbench tests
            name: sysbench max runtime seconds
          type:
            type_id: integer
        percentile:
          display:
            description: The percentile to report latency metrics
            name: sysbench latency percentile
          type:
            type_id: integer
        cpu-max-prime:
          display:
            description: The upper limit of the number of prime numbers generated
            name: sysbench cpu max primes
          type:
            type_id: integer
    SysbenchMemoryInputParams:
      id: SysbenchMemoryInputParams
      properties:
        threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        time:
          display:
            description: The maximum runtime in seconds for the sysbench tests
            name: sysbench max runtime seconds
          type:
            type_id: integer
        percentile:
          display:
            description: The percentile to report latency metrics
            name: sysbench latency percentile
          type:
            type_id: integer
        memory-block-size:
          display:
            description: The block size of data to transfer in KiB
            name: memory block size
          type:
            type_id: string
        memory-total-size:
          display:
            name: Total size of data to transfer in GiB
          required: false
          type:
            type_id: string
        memory-access-mode:
          display:
            description: The access mode into memory  seq or rnd
            name: memory access mode
          required: false
          type:
            type_id: enum_string
            values:
              rnd:
                name: RND
              seq:
                name: SEQ
        memory-oper:
          display:
            description: The memory operation  read or write
            name: memory operation
          required: false
          type:
            type_id: enum_string
            values:
              none:
                name: NONE
              read:
                name: READ
              write:
                name: WRITE
    PcpInputParams:
      id: PcpInputParams
      properties:
        pmlogger_interval:
          display:
            description: The logger collection interval for PCP pmlogger
            name: PCP pmlogger collection interval
          type:
            type_id: float
          required: false
          default: 1.0
    HorreumInputParams:
      id: HorreumInputParams
      properties:
        horreum_url:
          display:
            description: Base URL for the Horreum server.
            name: horreum url
          required: true
          type:
            pattern: ((http|https)\:\/\/)?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*
            type_id: string
        horreum_keycloak_url:
          display:
            description: Base URL for the Horreum Keycloak server.
            name: horreum keycloak url
          required: true
          type:
            pattern: ((http|https)\:\/\/)?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*
            type_id: string
        horreum_username:
          display:
            description: Username for the Horreum server.
            name: horreum username
          required: true
          type:
            type_id: string
        horreum_password:
          display:
            description: Password for the Horreum server.
            name: horreum password
          required: true
          type:
            type_id: string
        test_name:
          display:
            description: Name of the target test in Horreum for the object being
              uploaded.
            name: test name
          required: true
          type:
            type_id: string
        test_owner:
          display:
            description: Owner of the object being uploaded.
            name: test owner
          required: true
          type:
            type_id: string
        test_access_rights:
          display:
            description: Access rights for the object being uploaded.
            name: test access rights
          required: true
          type:
            type_id: enum_string
            values:
              PRIVATE:
                name: PRIVATE
              PROTECTED:
                name: PROTECTED
              PUBLIC:
                name: PUBLIC
    SysbenchLoopWorkflowInput:
      id: SysbenchLoopWorkflowInput
      properties:
        run_id:
          display:
            description: A unique run identifier for tracking groups of workflows triggered by external automation/CI
            name: Run ID
          type:
            type_id: string
          default: "\"\""
          required: false
        user:
          display:
            description: A user name identifier for tracking groups of workflows triggered by external automation/CI
            name: User
          type:
            type_id: string
          default: "\"\""
          required: false
        description:
          display:
            description: A description of the workflow being run
            name: Description
          type:
            type_id: string
          default: "\"\""
          required: false
        horreum_params:
          display:
            description: The parameters for uploading results to the Horreum server
            name: horreum parameters
          type:
            type_id: ref
            id: HorreumInputParams
        sysbench_cpu_tests:
          type:
            type_id: list
            items:
              type_id: object
              id: SysbenchCpuWorkflowInput
              properties:
                sysbench_params:
                  type:
                    type_id: ref
                    id: SysbenchCpuInputParams
                pcp_params:
                  type:
                    type_id: ref
                    id: PcpInputParams
        sysbench_memory_tests:
          type:
            type_id: list
            items:
              type_id: object
              id: SysbenchMemoryWorkflowInput
              properties:
                sysbench_params:
                  type:
                    type_id: ref
                    id: SysbenchMemoryInputParams
                pcp_params:
                  type:
                    type_id: ref
                    id: PcpInputParams

steps:
  uuidgen:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-utilities:0.5.0
    step: uuid
    input: {}
  system_config:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-metadata:0.4.0
    input: {}
  start_timestamp:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-utilities:0.5.0
    step: timestamp
    input: {}
  sysbench_cpu_loop:
    kind: foreach
    items: !expr $.input.sysbench_cpu_tests
    workflow: sysbench-cpu.yaml
    parallelism: 1
    wait_for: !expr $.steps.start_timestamp.outputs.success
  sysbench_memory_loop:
    kind: foreach
    items: !expr $.input.sysbench_memory_tests
    workflow: sysbench-memory.yaml
    parallelism: 1
    wait_for: !expr $.steps.sysbench_cpu_loop.outputs.success
  end_timestamp:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-utilities:0.5.0
    step: timestamp
    input: {}
    wait_for: !expr $.steps.sysbench_memory_loop.outputs.success
  # horreum_upload:
  #   plugin:
  #     deployment_type: image
  #     src: quay.io/arcalot/arcaflow-plugin-horreum-client:initial-design_ad15ed3
  #   input:
  #     horreum_url: !expr $.input.horreum_params.horreum_url
  #     horreum_keycloak_url: !expr $.input.horreum_params.horreum_keycloak_url
  #     horreum_username: !expr $.input.horreum_params.horreum_username
  #     horreum_password: !expr $.input.horreum_params.horreum_password
  #     test_name: !expr $.input.horreum_params.test_name
  #     test_owner: !expr $.input.horreum_params.test_owner
  #     test_access_rights: !expr $.input.horreum_params.test_access_rights
  #     test_start_time: "$.start_time"
  #     test_stop_time: "$.end_time"
  #     data_object:
  #       uuid: !expr $.steps.uuidgen.outputs.success.uuid
  #       run_id: !expr $.input.run_id
  #       user: !expr $.input.user
  #       description: !expr $.input.description
  #       start_time: !expr $.steps.start_timestamp.outputs.success.timestamp
  #       end_time: !expr $.steps.start_timestamp.outputs.success.timestamp
  #       system_config: !expr $.steps.system_config.outputs.success
  #       sysbench_cpu: !expr $.steps.sysbench_cpu_loop.outputs.success
  #       sysbench_memory: !expr $.steps.sysbench_memory_loop.outputs.success

outputs:
  success:
    uuid: !expr $.steps.uuidgen.outputs.success.uuid
    run_id: !expr $.input.run_id
    user: !expr $.input.user
    start_time: !expr $.steps.start_timestamp.outputs.success.timestamp
    end_time: !expr $.steps.start_timestamp.outputs.success.timestamp
    system_config: !expr $.steps.system_config.outputs.success
    sysbench_cpu: !expr $.steps.sysbench_cpu_loop.outputs.success
    sysbench_memory: !expr $.steps.sysbench_memory_loop.outputs.success
    # horreum_test_id: !expr $.steps.horreum_upload.outputs.success.horreum_test_id
