input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        kubeburner_es_server:
          display:
            description: List of ES instances
            name: es-server
          type:
            type_id: string
        kubeburner_es_index:
          display:
            description: The ElasticSearch index used to index the metrics
            name: es-index
          type:
            type_id: string
        kubeburner_qps:
          display:
            description: Max number of queries per second
            name: qps
          type:
            type_id: integer
        kubeburner_burst:
          display:
            description: Maximum burst for throttle
            name: burst
          type:
            type_id: integer
        kubeburner_loglevel:
          display:
            description: logging values- trace, debug, info, warn, error, fatal
            name: log-level
          type:
            type_id: string
        kubeburner_pods_per_node:
          display:
            description: Pods per node for node-density* workloads
            name: pods-per-node
          type:
            type_id: integer
        kubeburner_timeout:
          display:
            description: Benchmark timeout
            name: timeout
          type:
            type_id: string
        kubeburner_alerting:
          display:
            description: Enable alerting(true/false)
            name: alerting
          type:
            type_id: string
        kubeburner_gc:
          display:
            description: Garbage collect created namespaces(true/false)
            name: gc
          type:
            type_id: string
        kubeburner_pod_ready_threshold:
          display:
            description: Pod ready timeout threshold for node-density workload
            name: pod-ready-threshold
          type:
            type_id: string
        kubeconfig_str:
          display:
            description: Openshift cluster kubeconfig file content as a string
            name: kubeconfig
          type:
            type_id: string

steps:
  uuidgen:
    plugin: quay.io/arcalot/arcaflow-plugin-utilities:0.2.0
    step: uuid
    input: {}
  kubeburner:
    plugin: quay.io/redhat-performance/arcaflow-plugin-kube-burner:latest
    step: kube-burner
    input:
      workload: node-density
      uuid: !expr $.steps.uuidgen.outputs.success.uuid
      es_server: !expr $.input.kubeburner_es_server
      es_index: !expr $.input.kubeburner_es_index
      qps: !expr $.input.kubeburner_qps
      burst: !expr $.input.kubeburner_burst
      log_level: !expr $.input.kubeburner_loglevel
      pods_per_node: !expr $.input.kubeburner_pods_per_node
      timeout: !expr $.input.kubeburner_timeout
      gc: !expr $.input.kubeburner_gc
      alerting: !expr $.input.kubeburner_alerting
      pod_ready_threshold: !expr $.input.kubeburner_pod_ready_threshold
      kubeconfig: !expr $.input.kubeconfig_str
  metadata:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
    input: {}

output:
  uuid: !expr $.steps.uuidgen.outputs.success.uuid
  kubeburner: !expr $.steps.kubeburner.outputs.success
  metadata: !expr $.steps.metadata.outputs.success
