input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        # run_id, user, and cluster_name are simply metadata values that can be
        # used for record tracking
        run_id:
          display:
            description: A unique run identifier for tracking groups of workflows triggered by external automation/CI
            name: Run ID
          type:
            type_id: string
          default: "\"\""
          required: false
        user:
          display:
            description: A user name identifier for tracking groups of workflows triggered by external automation/CI
            name: User
          type:
            type_id: string
          default: "\"\""
          required: false
        cluster_name:
          display:
            description: A cluster name identifier for tracking groups of workflows triggered by external automation/CI
            name: Cluster Name
          type:
            type_id: string
          default: "\"\""
          required: false
        kb_pods_per_node:
          display:
            description: The number of pods per node for the kube-burner workloads
            name: pods per node
          type:
            type_id: integer
          default: 245
          required: false
        kb_timeout_minutes:
          display:
            description: The timeout for kube-burner in minutes
          type:
            #TODO -- Add the correct syntax for units interpretation
            type_id: integer
          default: 120
          required: false
        kb_log_level:
          display:
            description: The log level for kube-burner
          type:
            #TODO -- Make this an enum
            type_id: string
          default: 'info'
          required: false
        kb_cd_iterations:
          display:
            description: The number of iterations for kube-burner cluster-density tests
          type:
            type_id: integer
          default: 500
          required: false
        kb_cd_churn:
          display:
            description: Whether to use churn with kube-burner cluster-density tests
          type:
            type_id: boolean
          default: true
          required: false
        kb_cd_churn_delay:
          display:
            description: Churn delay for kube-burner cluster-density tests
          type:
            #TODO -- Convert to units
            type_id: string
          default: '2m'
          required: false
        kb_cd_churn_duration:
          display:
            description: Churn duration for kube-burner cluster-density tests
          type:
            #TODO -- Convert to units
            type_id: string
          default: '1h'
          required: false
        kb_cd_churn_percent:
          display:
            description: Churn percentage for kube-burner cluster-density tests
          type:
            type_id: integer
          default: 10
          required: false
      elastic_host:
          display:
            description: The host URL for the ElasticSearch service
            name: elasticsearch host url
          type:
            type_id: string
        # elastic_username:
        #   display:
        #     description: The username for the ElasticSearch service
        #     name: elasticsearch username
        #   type:
        #     type_id: string
        # elastic_password:
        #   display:
        #     description: The password for the ElasticSearch service
        #     name: elasticsearch password
        #   type:
        #     type_id: string
        elastic_index:
          display:
            description: The index for the ElasticSearch service
            name: elasticsearch index
          type:
            type_id: string
steps:
  uuidgen:
    plugin: quay.io/arcalot/arcaflow-plugin-utilities:0.2.0
    step: uuid
    input: {}
  # kubeconfig:
  #   plugin: quay.io/arcalot/arcaflow-plugin-kubeconfig:0.2.0
  #   input:
  #     kubeconfig: !expr $.input.kubeconfig
  # system_config:
  #   plugin: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
  #   input: {}
  node-density:
    plugin: http://quay.io/humesh/arcaflow-plugin-kube-burner:latest
    input:
      workload: 'node-density'
      uuid: !expr $.steps.uuidgen.outputs.success
      pods_per_node: !expr $.input.kb_pods_per_node
      timeout: !expr $.input.kb_timeout_minutes
      # Note this value is only used in this step, and is hard-coded here
      pod_ready_threshold: '20s'
      es_server: !expr $.input.elastic_host
      es_index: !expr $.input.elastic_index
      log_level: !expr $.input.kb_log_level
      kubeconfig: !expr $.input.kubeconfig
  node-density-heavy:
    plugin: http://quay.io/humesh/arcaflow-plugin-kube-burner:latest
    input:
      workload: 'node-density-heavy'
      uuid: !expr $.steps.uuidgen.outputs.success
      pods_per_node: !expr $.input.kb_pods_per_node
      timeout: !expr $.input.kb_timeout_minutes
      es_server: !expr $.input.elastic_host
      es_index: !expr $.input.elastic_index
      log_level: !expr $.input.kb_log_level
      kubeconfig: !expr $.input.kubeconfig
  node-density-cni:
    plugin: http://quay.io/humesh/arcaflow-plugin-kube-burner:latest
    input:
      workload: 'node-density-cni'
      uuid: !expr $.steps.uuidgen.outputs.success
      pods_per_node: !expr $.input.kb_pods_per_node
      timeout: !expr $.input.kb_timeout_minutes
      es_server: !expr $.input.elastic_host
      es_index: !expr $.input.elastic_index
      log_level: !expr $.input.kb_log_level
      kubeconfig: !expr $.input.kubeconfig
  cluster-density:
    plugin: http://quay.io/humesh/arcaflow-plugin-kube-burner:latest
    input:
      workload: 'cluster-density'
      uuid: !expr $.steps.uuidgen.outputs.success
      iterations: !expr $.input.kb_cd_iterations
      timeout: !expr $.input.kb_timeout_minutes
      churn: !expr $.input.kb_cd_churn
      churn-delay: !expr $.input.kb_cd_churn_delay
      churn-duration: !expr $.input.kb_cd_churn_duration
      churn-percent: !expr $.input.kb_cd_churn_percent
      es_server: !expr $.input.elastic_host
      es_index: !expr $.input.elastic_index
      log_level: !expr $.input.kb_log_level
      kubeconfig: !expr $.input.kubeconfig
output:
  uuid: !expr $.steps.uuidgen.outputs.success.uuid
  run_id: !expr $.input.run_id
  user: !expr $.input.user
  cluster_name: !expr $.input.cluster_name
  elasticsearch_host: !expr $.input.elastic_host
  elasticsearch_index: !expr $.input.elastic_index
  node-density: !expr $.steps.node-density.outputs.success
  node-density-heavy: !expr $.steps.node-density.outputs.success
  node-density-cni: !expr $.steps.node-density.outputs.success
  cluster-density: !expr $.steps.node-density.outputs.successsuccess
